import type { DocModule } from "./docs-types";
import type { Product } from "./products";

/**
 * Every doc this host serves, and how to load it.
 *
 * The specifiers are literal because a bundler cannot follow an import built
 * from a variable, which is the whole reason this list exists rather than a
 * directory read at request time. Keyed by product first: two sections are free
 * to both ship an `overview`, and the route resolves one before the other.
 *
 * The spendgraph pages load from the published packages, so a doc is written
 * once — beside the code it documents — and this host renders whichever version
 * is installed.
 */
export const DOCS: Record<Product, Record<string, () => Promise<DocModule>>> = {
  locusgraph: {
    concepts: () => import("@/content/locusgraph/concepts.mdx"),
    "enterprise/data-residency": () => import("@/content/locusgraph/enterprise/data-residency.mdx"),
    "enterprise/deployment": () => import("@/content/locusgraph/enterprise/deployment.mdx"),
    "enterprise/security": () => import("@/content/locusgraph/enterprise/security.mdx"),
    "enterprise/sso": () => import("@/content/locusgraph/enterprise/sso.mdx"),
    "enterprise/support": () => import("@/content/locusgraph/enterprise/support.mdx"),
    "recall/deep-recall": () => import("@/content/locusgraph/recall/deep-recall.mdx"),
    "recall/options": () => import("@/content/locusgraph/recall/options.mdx"),
    "recall/results": () => import("@/content/locusgraph/recall/results.mdx"),
    "recall/search": () => import("@/content/locusgraph/recall/search.mdx"),
    "contexts/browsing": () => import("@/content/locusgraph/contexts/browsing.mdx"),
    "contexts/linking": () => import("@/content/locusgraph/contexts/linking.mdx"),
    "contexts/overview": () => import("@/content/locusgraph/contexts/overview.mdx"),
    "contexts/resolving": () => import("@/content/locusgraph/contexts/resolving.mdx"),
    "review/decisions": () => import("@/content/locusgraph/review/decisions.mdx"),
    "review/inbox": () => import("@/content/locusgraph/review/inbox.mdx"),
    "review/observe": () => import("@/content/locusgraph/review/observe.mdx"),
    "graphs/access": () => import("@/content/locusgraph/graphs/access.mdx"),
    "graphs/create": () => import("@/content/locusgraph/graphs/create.mdx"),
    "graphs/keys": () => import("@/content/locusgraph/graphs/keys.mdx"),
    "graphs/settings": () => import("@/content/locusgraph/graphs/settings.mdx"),
    "remember/batch": () => import("@/content/locusgraph/remember/batch.mdx"),
    "remember/deleting": () => import("@/content/locusgraph/remember/deleting.mdx"),
    "remember/event-kinds": () => import("@/content/locusgraph/remember/event-kinds.mdx"),
    "remember/sources": () => import("@/content/locusgraph/remember/sources.mdx"),
    "remember/store": () => import("@/content/locusgraph/remember/store.mdx"),
    "client/connecting": () => import("@/content/locusgraph/client/connecting.mdx"),
    "client/versioning": () => import("@/content/locusgraph/client/versioning.mdx"),
    "client/errors": () => import("@/content/locusgraph/client/errors.mdx"),
    "client/install": () => import("@/content/locusgraph/client/install.mdx"),
    "client/limits": () => import("@/content/locusgraph/client/limits.mdx"),
    "client/types": () => import("@/content/locusgraph/client/types.mdx"),
    "use-cases/agent-skills": () => import("@/content/locusgraph/use-cases/agent-skills.mdx"),
    "use-cases/conversations": () => import("@/content/locusgraph/use-cases/conversations.mdx"),
    "use-cases/documents": () => import("@/content/locusgraph/use-cases/documents.mdx"),
    "use-cases/multi-tenant": () => import("@/content/locusgraph/use-cases/multi-tenant.mdx"),
    "use-cases/preferences": () => import("@/content/locusgraph/use-cases/preferences.mdx"),
    "use-cases/team-knowledge": () => import("@/content/locusgraph/use-cases/team-knowledge.mdx"),
    quickstart: () => import("@/content/locusgraph/quickstart.mdx"),
    overview: () => import("@/content/locusgraph/overview.mdx"),
  },
  spendgraph: {
    concepts: () => import("@/content/spendgraph/concepts.mdx"),
    "getting-started": () => import("@/content/spendgraph/getting-started.mdx"),
    overview: () => import("@/content/spendgraph/overview.mdx"),
    "cli/commands": () => import("@spendgraph/docs/cli/commands.mdx"),
    "cli/credentials": () => import("@spendgraph/docs/cli/credentials.mdx"),
    "cli/output": () => import("@spendgraph/docs/cli/output.mdx"),
    "cli/overview": () => import("@spendgraph/docs/cli/overview.mdx"),
    "cli/skills": () => import("@spendgraph/docs/cli/skills.mdx"),
    "evals/comparing-runs": () => import("@spendgraph/docs/evals/comparing-runs.mdx"),
    "evals/datasets": () => import("@spendgraph/docs/evals/datasets.mdx"),
    "evals/getting-started": () => import("@spendgraph/docs/evals/getting-started.mdx"),
    "evals/judge": () => import("@spendgraph/docs/evals/judge.mdx"),
    "evals/metrics": () => import("@spendgraph/docs/evals/metrics.mdx"),
    "evals/metrics/criteria": () => import("@spendgraph/docs/evals/metrics/criteria.mdx"),
    "evals/metrics/custom": () => import("@spendgraph/docs/evals/metrics/custom.mdx"),
    "evals/metrics/deterministic": () => import("@spendgraph/docs/evals/metrics/deterministic.mdx"),
    "evals/metrics/retrieval": () => import("@spendgraph/docs/evals/metrics/retrieval.mdx"),
    "graph/nodes": () => import("@spendgraph/docs/graph/nodes.mdx"),
    "graph/overview": () => import("@spendgraph/docs/graph/overview.mdx"),
    "graph/pausing": () => import("@spendgraph/docs/graph/pausing.mdx"),
    "graph/running": () => import("@spendgraph/docs/graph/running.mdx"),
    "graph/streaming": () => import("@spendgraph/docs/graph/streaming.mdx"),
    "graph/wiring": () => import("@spendgraph/docs/graph/wiring.mdx"),
    "harness/cascade": () => import("@spendgraph/docs/harness/cascade.mdx"),
    "harness/chain": () => import("@spendgraph/docs/harness/chain.mdx"),
    "harness/choosing": () => import("@spendgraph/docs/harness/choosing.mdx"),
    "harness/human-in-the-loop": () => import("@spendgraph/docs/harness/human-in-the-loop.mdx"),
    "harness/loop": () => import("@spendgraph/docs/harness/loop.mdx"),
    "harness/orchestrate": () => import("@spendgraph/docs/harness/orchestrate.mdx"),
    "harness/overview": () => import("@spendgraph/docs/harness/overview.mdx"),
    "harness/parallel": () => import("@spendgraph/docs/harness/parallel.mdx"),
    "harness/refine": () => import("@spendgraph/docs/harness/refine.mdx"),
    "harness/route": () => import("@spendgraph/docs/harness/route.mdx"),
    "harness/streaming": () => import("@spendgraph/docs/harness/streaming.mdx"),
    "llms/calling": () => import("@spendgraph/docs/llms/calling.mdx"),
    "llms/overview": () => import("@spendgraph/docs/llms/overview.mdx"),
    "llms/providers": () => import("@spendgraph/docs/llms/providers.mdx"),
    "llms/streaming": () => import("@spendgraph/docs/llms/streaming.mdx"),
    "llms/structured-output": () => import("@spendgraph/docs/llms/structured-output.mdx"),
    "llms/tools": () => import("@spendgraph/docs/llms/tools.mdx"),
    "prompt/caching": () => import("@spendgraph/docs/prompt/caching.mdx"),
    "prompt/calling": () => import("@spendgraph/docs/prompt/calling.mdx"),
    "prompt/datasets": () => import("@spendgraph/docs/prompt/datasets.mdx"),
    "prompt/fields": () => import("@spendgraph/docs/prompt/fields.mdx"),
    "prompt/overview": () => import("@spendgraph/docs/prompt/overview.mdx"),
    "prompt/running": () => import("@spendgraph/docs/prompt/running.mdx"),
    "sdk/api": () => import("@spendgraph/docs/sdk/api.mdx"),
    "sdk/budgets": () => import("@spendgraph/docs/sdk/budgets.mdx"),
    "sdk/integrations": () => import("@spendgraph/docs/sdk/integrations.mdx"),
    "sdk/quickstart": () => import("@spendgraph/docs/sdk/quickstart.mdx"),
    "sdk/client": () => import("@spendgraph/docs/sdk/client.mdx"),
    "sdk/errors": () => import("@spendgraph/docs/sdk/errors.mdx"),
    "sdk/tracking": () => import("@spendgraph/docs/sdk/tracking.mdx"),
    "stage/cost": () => import("@spendgraph/docs/stage/cost.mdx"),
    "stage/events": () => import("@spendgraph/docs/stage/events.mdx"),
    "stage/overview": () => import("@spendgraph/docs/stage/overview.mdx"),
    "stage/retrying": () => import("@spendgraph/docs/stage/retrying.mdx"),
    "stage/running": () => import("@spendgraph/docs/stage/running.mdx"),
    "tools/bogus": () => import("@spendgraph/docs/tools/bogus.mdx"),
    "tools/builtins": () => import("@spendgraph/docs/tools/builtins.mdx"),
    "tools/bus": () => import("@spendgraph/docs/tools/bus.mdx"),
    "tools/declaring": () => import("@spendgraph/docs/tools/declaring.mdx"),
    "tools/effects": () => import("@spendgraph/docs/tools/effects.mdx"),
    "tools/overview": () => import("@spendgraph/docs/tools/overview.mdx"),
    "tools/selecting": () => import("@spendgraph/docs/tools/selecting.mdx"),
    "tools/stored": () => import("@spendgraph/docs/tools/stored.mdx"),
    "tools/turns": () => import("@spendgraph/docs/tools/turns.mdx"),
    "vigil/agents": () => import("@spendgraph/docs/vigil/agents.mdx"),
    "vigil/failures": () => import("@spendgraph/docs/vigil/failures.mdx"),
    "vigil/getting-started": () => import("@spendgraph/docs/vigil/getting-started.mdx"),
    "vigil/hosts": () => import("@spendgraph/docs/vigil/hosts.mdx"),
    "vigil/testing": () => import("@spendgraph/docs/vigil/testing.mdx"),
    "vigil/workflows": () => import("@spendgraph/docs/vigil/workflows.mdx"),
  },
  brainstorm: {},
  "locus-skill": {},
};
